#pragma once

#define LOCAL_APIC_ID 0x20
#define LOCAL_APIC_VERSION 0x30
#define LOCAL_APIC_TRR 0x80
#define LOCAL_APIC_APR 0x90
#define LOCAL_APIC_PPR 0xA0
#define LOCAL_APIC_EOI 0xB0
#define LOCAL_APIC_RRD 0xC0
#define LOCAL_APIC_LDR 0xD0
#define LOCAL_APIC_DFR 0xE0
#define LOCAL_APIC_SIVR 0xF0
#define LOCAL_APIC_ISR 0x100
#define LOCAL_APIC_TMR 0x180
#define LOCAL_APIC_IRR 0x200
#define LOCAL_APIC_ERROR_STATUS 0x280
#define LOCAL_APIC_CMCI 0x2F0
#define LOCAL_APIC_ICR 0x300
#define LOCAL_APIC_LVT_TIMER 0x320
#define LOCAL_APIC_LVT_THERMAL 0x330
#define LOCAL_APIC_LVT_PERF_MONITORING 0x340
#define LOCAL_APIC_LVT_LINT0 0x350
#define LOCAL_APIC_LVT_LINT1 0x360
#define LOCAL_APIC_LVT_ERROR 0x370
#define LOCAL_APIC_TIMER_INITIAL_COUNT 0x380
#define LOCAL_APIC_TIMER_CURRENT_COUNT 0x390
#define LOCAL_APIC_TIMER_DIVIDE 0x3E0

#define LOCAL_APIC_BASE 0xFFFFFFFFFF000

namespace APIC{
    namespace Local{

    }

    namespace IO{

    }

    int Initialize();
}