#!/bin/sh
export TOOLCHAIN_PATH="$HOME/.local/share/lemon/bin"
SPATH=$(dirname $(readlink -f "$0"))
source $SPATH/env.sh

if ! [ -x "$(command -v lemon-clang)" ]; then
    echo "Lemon cross toolchain not found (Did you forget to build toolchain?)"
    exit 1
fi

set -e 1

mkdir -p $HOME/.local/share/lemon/sysroot/system/lib
mkdir -p $HOME/.local/share/lemon/sysroot/system/include
mkdir -p $HOME/.local/share/lemon/sysroot/system/bin

ln -sfT ../../../include/c++ $HOME/.local/share/lemon/sysroot/system/include/c++
cp $HOME/.local/share/lemon/lib/x86_64-unknown-lemon/*.so* $HOME/.local/share/lemon/sysroot/system/lib

cd $SPATH/..

echo "# Generated by Scripts/configure.sh
[binaries]
c = '$TOOLCHAIN_PATH/lemon-clang'
cpp = '$TOOLCHAIN_PATH/lemon-clang++'
ar = '$TOOLCHAIN_PATH/x86_64-lemon-ar'
strip = '$TOOLCHAIN_PATH/x86_64-lemon-strip'
ld = '$TOOLCHAIN_PATH/x86_64-lemon-ld'
pkgconfig = '$SPATH/pkg-config'

[host_machine]
system = 'lemon'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[built-in options]
prefix = '$HOME/.local/share/lemon/sysroot/system'" > $SPATH/lemon-crossfile.txt

cd $SPATH
$SPATH/libc.sh

cd "$LEMON_BUILDROOT/Ports"
./buildport.sh zlib
./buildport.sh libpng
./buildport.sh freetype
./buildport.sh libressl

cd $SPATH/..

meson Build --cross $SPATH/lemon-crossfile.txt
$SPATH/buildinterfaces.sh
