SPATH=$(dirname $(readlink -f "$0"))
export LEMOND="$SPATH/.."

if [ -z "$LEMON_SYSROOT" ]; then
    export LEMON_SYSROOT=$HOME/.local/share/lemon/sysroot
fi

export TOOLCHAIN_PATH="$HOME/.local/share/lemon/bin"
export PATH="$TOOLCHAIN_PATH:$PATH"

if ! [ -x "$(command -v lemon-clang)" ]; then
    echo "Lemon cross toolchain not found (Did you forget to build toolchain?)"
    exit 1
fi

set -e

ln -sfT ../../../include/c++ $HOME/.local/share/lemon/sysroot/system/include/c++
cp $HOME/.local/share/lemon/lib/x86_64-lemon/c++/*.so* $HOME/.local/share/lemon/sysroot/system/lib

cd $SPATH
$SPATH/libc.sh

cd $SPATH/..

echo "# Generated by Scripts/configure.sh
[binaries]
c = '$TOOLCHAIN_PATH/lemon-clang'
cpp = '$TOOLCHAIN_PATH/lemon-clang++'
ar = '$TOOLCHAIN_PATH/x86_64-lemon-ar'
strip = '$TOOLCHAIN_PATH/x86_64-lemon-strip'
ld = '$TOOLCHAIN_PATH/x86_64-lemon-ld'

[host_machine]
system = 'lemon'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[built-in options]
prefix = '~/.local/share/lemon/sysroot/system'" > $SPATH/lemon-crossfile.txt

meson Build --cross $SPATH/lemon-crossfile.txt
$SPATH/buildinterfaces.sh

cd "$LEMOND/Ports"
./buildport.sh zlib
./buildport.sh libpng
./buildport.sh freetype
./buildport.sh libressl
